 sudo: required
 dist: precise
 language: cpp

 matrix:
    include:
        - compiler: gcc
          addons:
            apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - g++-4.9
          env: COMPILER=g++-4.9
    include:
        - compiler: gcc
          addons:
            apt:
              sources:
                  - ubuntu-toolchain-r-test
              packages:
                  - g++-5
          env: COMPILER=g++-5

 before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -y qt4-dev-tools

 script: 
   - mkdir build
   - cd build
   - qmake -o makefile ../minotaur.pro
   - make
 
 notifications:
  slack: uwnrg:zSxSzV4CSAa1o8tA6jjMCJSP
