 addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
            - qt4-dev-tools

 language: cpp

 compiler: gcc

 before_script:
   - mkdir build
   - cd build
   - qmake -o makefile ../minotaur.pro

 script: make
 
 notifications:
  slack: uwnrg:zSxSzV4CSAa1o8tA6jjMCJSP
