 language: cpp

 compiler: gcc

 before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default qttools5-dev-tools

 before_script:
   - mkdir build
   - cd build
   - qmake ..\minotaur.pro -r "CONFIG+=debug" "CONFIG+=qml_debug"

 script: make
